### ISSUE TITLE
[jaxrs-cxf] Guaranteed MalformedURLException

### ISSUE THREAD

**Issue by demonfiddler** [swagger-api/swagger-codegen-generators#138]
AbstractJavaJAXRSServerCodegen always logs a needless warning-level MalformedURLException for a valid OAS 2.0 YAML, because according to the OAS 2.0 specification for basePath: "The value MUST start with a leading slash (/)", which can never be a valid URL and will thus always throw MalformedURLException.

[WARNING] Not valid URL: /v1/dt
java.net.MalformedURLException: no protocol: /v1/dt
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.swagger.codegen.utils.URLPathUtil.getServerURL(URLPathUtil.java:30)
	at io.swagger.codegen.languages.java.AbstractJavaJAXRSServerCodegen.preprocessOpenAPI(AbstractJavaJAXRSServerCodegen.java:92)
	at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:201)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

**Comment by HugoMario** [comment]
thanks, @demonfiddler these days i'm really busy but i'm going to try to address this as soon i can.
